spring:
  application:
    name: frontend
  server:
    port: 8080
  thymeleaf:
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html